### PR TITLE
Update mavlink definitions

### PR DESCRIPTION
**Pull request by TheKeveloper**
This updates mavlink to the latest definitions with a few omissions:
all.xml
development.xml
minimal.xml
python_array_test.xml
storm32.xml
test.xml

I instead embed the minimal.xml definitions directly into common.xml because the generator does not currently work properly with enum includes that are referenced in other messages. storm32.xml is omitted because it also includes other definitions. The remainder are omitted because they are mostly in development or testing rather than being officially part of the mavlink message definitions.

The changes in this PR are just a result of running ./gradlew build in the main repo with the updated xml files.

### CODE REVIEW

**Comment by benbarkay** [comment]
Hi, thank you for this. I'll merge this in, but it might take me a while to make a release.

**Comment by TheKeveloper** [comment]
> Hi, thank you for this. I'll merge this in, but it might take me a while to make a release.

Thank you! And makes sense. I know this hasn't been updated in a while so no worries if it takes some time to release.

**Comment by TheKeveloper** [comment]
Hey @benbarkay, wanted to check in to see if you have some estimate of a timeline for getting a new release published? No rush obviously, but it would just help me in deciding some approaches to take (e.g. if you are planning a release in a week or two, I will just wait for the release. If you are planning a release in 6 months, I'll probably try to find some workaround to get some of the newer messages in).

**Comment by benbarkay** [comment]
I've eventually ended up fixing some problems with dialect generation, which I suppose you had to work around yourself. I've released `1.1.11` to central, it should be available within the next hour or so.

**Comment by TheKeveloper** [comment]
@benbarkay thanks so much! Although I still don't see `1.1.11` on central? It's possible that it's just some delay or I'm not looking in the right place...

**Comment by benbarkay** [comment]
@TheKeveloper 
It's my bad actually, I didn't release after closing the staging repo on sonatype. Haven't done this manually in a while lol.

**Comment by TheKeveloper** [comment]
@benbarkay managed to get the new dependency! Thank you so much!!

**Pull request merged**
